
# my_columns = [{'primary': True, 'title': 'ERP Customer Name', 'type': 'TEXT_NUMBER'},
#               {'title': 'End Customer Ultimate Name', 'type': 'TEXT_NUMBER'},
#               {'title': 'col1', 'type': 'CHECKBOX', 'symbol': 'STAR'}]

search_tags = [{'primary': True, 'title': 'Bill To ID:', 'type': 'TEXT_NUMBER'},
               {'title': 'Partner Account Name:', 'type': 'TEXT_NUMBER'},
               {'title': 'End Customer Name:', 'type': 'TEXT_NUMBER'},
               {'title': 'Subscription Reference ID:', 'type': 'TEXT_NUMBER'},
               {'title': 'CCW Web Order ID:', 'type': 'TEXT_NUMBER'},
               {'title': 'Ship To ID:', 'type': 'TEXT_NUMBER'},
               {'title': 'Order Contact First Name:', 'type': 'TEXT_NUMBER'},
               {'title': 'Order Contact Last Name:', 'type': 'TEXT_NUMBER'},
               {'title': 'Order Contact Email:', 'type': 'TEXT_NUMBER'},
               {'title': 'Order Contact Phone:', 'type': 'TEXT_NUMBER'},
               {'title': 'Billing Contact First Name:', 'type': 'TEXT_NUMBER'},
               {'title': 'Billing Contact Last Name:', 'type': 'TEXT_NUMBER'},
               {'title': 'Billing Contact Email:', 'type': 'TEXT_NUMBER'},
               {'title': 'Billing Contact Phone:', 'type': 'TEXT_NUMBER'},
               {'title': 'Reseller Contact First Name:', 'type': 'TEXT_NUMBER'},
               {'title': 'Reseller Contact Last Name:', 'type': 'TEXT_NUMBER'},
               {'title': 'Reseller Contact Email:', 'type': 'TEXT_NUMBER'},
               {'title': 'Reseller Contact Phone:', 'type': 'TEXT_NUMBER'},
               {'title': 'Service To Contact First Name:', 'type': 'TEXT_NUMBER'},
               {'title': 'Service To Contact Last Name:', 'type': 'TEXT_NUMBER'},
               {'title': 'Service To Contact Phone:', 'type': 'TEXT_NUMBER'},
               {'title': 'Initial Term:', 'type': 'TEXT_NUMBER'},
               {'title': 'Renewal Term:', 'type': 'TEXT_NUMBER'},
               {'title': 'Prepayment Term:', 'type': 'TEXT_NUMBER'},
               {'title': 'Billing Model:', 'type': 'TEXT_NUMBER'},
               {'title': 'MRR:', 'type': 'TEXT_NUMBER'},
               {'title': 'Route to Market:', 'type': 'TEXT_NUMBER'},
               {'title': 'Service Requested Start Date:', 'type': 'TEXT_NUMBER'}]